### ISSUE TITLE
[Meta] Beta release of localgov_microsites

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#330]
We want to tag a beta release this week fir localgov_microsites.

It would therefore be good to be able to release a beta tag for each of these modules: 

- [x] https://github.com/localgovdrupal/localgov_microsites
- [x] https://github.com/localgovdrupal/localgov_page
- [x] https://github.com/localgovdrupal/localgov_sa11y
- [x] https://github.com/localgovdrupal/localgov_microsites_base
- [x] https://github.com/localgovdrupal/localgov_microsites_group
- [x] https://github.com/localgovdrupal/localgov_microsites_colour_picker_fields
- [x] https://github.com/localgovdrupal/localgov_microsites_project
- [x] https://github.com/localgovdrupal/group_webform - "localgovdrupal/group_webform": "1.x-dev",

We also rely on these modules, currently at varying states of release: 

- https://www.drupal.org/project/group  "drupal/group": "3.0.x-dev",
- https://www.drupal.org/project/group_content_menu "drupal/group_content_menu": "3.x-dev",
- https://www.drupal.org/project/group_permissions  "drupal/group_permissions": "2.0.x-dev",
- https://www.drupal.org/project/group_term "drupal/group_term": "dev-3316529-group-3.x-compatibility",
- https://www.drupal.org/project/domain_group/ 
(request for maintainership https://www.drupal.org/project/domain_group/issues/3325392 )

Beta blocking issues: 

- [x] https://github.com/localgovdrupal/localgov_microsites_group/issues/355
- [x] https://github.com/localgovdrupal/localgov_microsites/issues/333 
- [x] https://github.com/localgovdrupal/localgov_microsites_group/issues/338
- [x] https://github.com/localgovdrupal/localgov_microsites_group/issues/364
- [x] https://github.com/localgovdrupal/localgov_microsites/issues/334
