### ISSUE TITLE
[Meta] stable release for localgov_microsites 4.0.0

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites#378]
@stephen-cox mentioned it would be good to have a pathway towards a stable release for localgov_microsites

@ekes mentioned that a few of the group ecosystem modules we use are using are still on the dev branches. 

We can list out all the dev and non stable modules here are make a call as to which we need for a stable release.

We'll want to review and merge the following:

- [x] https://github.com/localgovdrupal/localgov_microsites/pull/425
- [x] https://github.com/localgovdrupal/localgov_microsites_group/pull/459
- [x] https://github.com/localgovdrupal/localgov_microsites_project/pull/36
- [x] https://github.com/localgovdrupal/localgov_microsites_project/pull/46
- [x] https://github.com/localgovdrupal/localgov_microsites_group/issues/428
- [x] https://github.com/localgovdrupal/localgov_microsites_group/issues/464
- [x] https://github.com/localgovdrupal/localgov_microsites_group/issues/473
- [x] https://github.com/localgovdrupal/localgov_microsites/issues/483

Then hopefully all our tests will be passing and we can review for a beta or stable release.

Note we are no longer including the following: 

- [ ] ~https://github.com/localgovdrupal/localgov_microsites_group/pull/461~
- [ ] ~https://github.com/localgovdrupal/localgov_microsites_project/pull/48~

**Comment by finnlewis** [comment]
We have a fair few live sites now: 
Including: 
 - https://www.croydonlcsb.org.uk/
 - https://www.haringeyfeast.com/
 - https://jobs.oxfordshire.gov.uk/
 - https://investwalthamforest.com/

Ekes: mentioned that we probably want a stable release of https://www.drupal.org/project/domain_group too.

**Comment by finnlewis** [comment]
I think we're nearly there. 

(See the original post for list of issues)

**Comment by ekes** [comment]
Just added https://github.com/localgovdrupal/localgov_microsites_group/issues/473 to the list because I think that's another important one. Handling webform creation etc. can be post stable enhancement, but the submissions, we need tests for before that.

**Comment by ekes** [comment]
Don't know if this is considered a requirement. It's pretty irritating.
 - [ ] https://github.com/localgovdrupal/localgov_microsites_group/issues/475
 
 Basically mean in the list of vocabularies you have ones listed that don't exist on your multi-site; and when you click on them you are taken to a page with an empty list.

**Comment by finnlewis** [comment]
I think once this one is merged, we might be ready for a stable release: https://github.com/localgovdrupal/localgov_microsites_group/pull/479

**Comment by ekes** [comment]
> Don't know if this is considered a requirement. It's pretty irritating.
> 
>     * [ ]  [Term UI doesn't check if the terms are enabled localgov_microsites_group#475](https://github.com/localgovdrupal/localgov_microsites_group/issues/475)
> 
> 
> Basically mean in the list of vocabularies you have ones listed that don't exist on your multi-site; and when you click on them you are taken to a page with an empty list.

Vocabularies are no longer listed. Just tested clean site switching off Events and Blogs and their related vocabularies disappear from the vocabularies list.

So I'll take this one off the blockers list.

**Comment by finnlewis** [comment]
Just added https://github.com/localgovdrupal/localgov_microsites/issues/483
